inputs:
  python_version:
    type: string
    description: Specify python version for bootstrap
    default:

pipeline:
  - step: CreateVEnv
    module: pypeline.steps.create_venv
    config:
      python_version: 3.13
      python_package_manager: uv>=0
  - step: GenerateEnvSetupScript
    module: pypeline.steps.env_setup_script
  - step: PreCommit
    run: pre-commit run --all-files
  - step: PyTest
    run: pytest
